### PR TITLE
update

### PR DESCRIPTION
**Pull request by Harsh-Singh007**

### CODE REVIEW

**Comment by linhaow** [comment]
我已经收到了您的邮件，祝您生活愉快~                          --林浩文

**Comment by ashwinvargh** [comment]
I respect the agency. Will view soon.

**Comment by ashwinvargh** [comment]
JS. The page isn't loading right now.

**Comment by Harsh-Singh007** [comment]
> 我已经收到了您的邮件，祝您生活愉快~                          --林浩文

thanks and same to you

**Comment by ashwinvargh** [comment]
Your page still doesn't load...send me a pdf.

Thanks,
Ashwin

**Pull request closed without merging**
